# Change these first
owner: Saboor-Hakimi # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Afghan ChatGPT
    url: https://saboor.rocks
  - name: ASEELAPP
    url: https://aseelapp.com
  - name: Jobs.af
    url: https://jobs.af
  - name: Login to HesabPay
    url: https://api.hesab.af/2.0/api/login
    method: POST
  - name: HEMIS
    check: "tcp-ping"
    url: 149.54.12.140
    port: 22



status-website: # Status website (optional)
  cname: upptime.saboor.rocks # Custom domain CNAME
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/Saboor-Hakimi/upptime). No server required — just GitHub Actions, Issues, and Pages.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/Saboor-Hakimi/upptime

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
